name: Hello World Workflow

# This specifies when the action should be triggered. In this case, on every push.
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest  # The runner (environment) to use. Ubuntu in this case.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # This action checks out your repository files.

      - name: Print Hello World
        run: echo "Hello, World!"

  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.7.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: python -m pip install poetry==1.1.11

      - name: Configure poetry
        run: python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: python -m poetry install

      - name: View poetry --help
        run: poetry --help
